name: Release Obsidian Plugin

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+" # Matches standard semantic version tags without "v" prefix

permissions:
    contents: write # This gives permission to create releases

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Get version from tag
              id: get_version
              run: |
                  # Extract version from tag
                  VERSION=${GITHUB_REF_NAME#v}
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
                  echo "Building release for version: $VERSION"

            - name: Install dependencies
              run: bun install

            - name: Build plugin
              run: bun run build

            - name: Verify versions match
              run: |
                  # Check if tag version matches package.json, manifest.json and exists in versions.json
                  PKG_VERSION=$(node -p "require('./package.json').version")
                  MANIFEST_VERSION=$(node -p "require('./manifest.json').version")

                  if [[ "$PKG_VERSION" != "$VERSION" ]]; then
                    echo "⚠️ Warning: Tag version ($VERSION) doesn't match package.json version ($PKG_VERSION)"
                  fi

                  if [[ "$MANIFEST_VERSION" != "$VERSION" ]]; then
                    echo "⚠️ Warning: Tag version ($VERSION) doesn't match manifest.json version ($MANIFEST_VERSION)"
                  fi

                  if ! node -e "const vs=require('./versions.json'); if(!vs['$VERSION']) throw 'Version not found'"; then
                    echo "⚠️ Warning: Version $VERSION not found in versions.json"
                  fi
            - name: Update CHANGELOG
              id: changelog
              uses: requarks/changelog-action@v1
              with:
                  token: ${{ github.token }}
                  tag: ${{ env.VERSION }}

            - name: Package plugin
              run: |
                  mkdir -p release
                  cp main.js manifest.json versions.json release/
                  if [ -f styles.css ]; then cp styles.css release/; fi

                  # Create zip file
                  cd release
                  zip -r obsidian-selected-to-unique-note-$VERSION.zip ./*
                  mv obsidian-selected-to-unique-note-$VERSION.zip ../
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: obsidian-selected-to-unique-note-*.zip
                  name: Version ${{ env.VERSION }}
                  body: |
                      ## Selected to Unique Note v${{ env.VERSION }}

                      Please refer to the [changelog](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for details.

                      ### Changes
                      ${{ steps.changelog.outputs.changes }}

                      ### Installation
                      1. Download the release zip file
                      2. Unzip in your Obsidian vault's plugins folder: `.obsidian/plugins/`
                      3. Enable the plugin in Obsidian settings
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit CHANGELOG.md
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: master
                  commit_message: "docs: update CHANGELOG.md for v${{ env.VERSION }} [skip ci]"
                  file_pattern: CHANGELOG.md
